# Code challenge: Decision trees
© ExploreAI Academy

In this code challenge, we will test our knowledge of the fundamental concepts of decision trees by implementing a decision tree regression model and analysing its RMSLE.



We begin by importing the necessary packages for the challenges.

In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

## The dataset

The dataset contains population data for various countries over the years from 1960 to 2017. Each row corresponds to a specific country, identified by a country code, and each column represents a year. The values within the dataset represent the population count for each country in the corresponding year.

In [2]:
population_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/world_population.csv', index_col='Country Code')
population_df.head()

1960       1961       1962       1963       1964  \
Country Code                                                          
ABW             54211.0    55438.0    56225.0    56695.0    57032.0   
AFG           8996351.0  9166764.0  9345868.0  9533954.0  9731361.0   
AGO           5643182.0  5753024.0  5866061.0  5980417.0  6093321.0   
ALB           1608800.0  1659800.0  1711319.0  1762621.0  1814135.0   
AND             13411.0    14375.0    15370.0    16412.0    17469.0   

                   1965        1966        1967        1968        1969  ...  \
Country Code                                                             ...   
ABW             57360.0     57715.0     58055.0     58386.0     58726.0  ...   
AFG           9938414.0  10152331.0  10372630.0  10604346.0  10854428.0  ...   
AGO           6203299.0   6309770.0   6414995.0   6523791.0   6642632.0  ...   
ALB           1864791.0   1914573.0   1965598.0   2022272.0   2081695.0  ...   
AND             18549.0     19647.0     20758.0     21890.0     23058.0  ...   

                    2008        2009        2010        2011        2012  \
Country Code                                                               
ABW             101353.0    101453.0    101669.0    102053.0    102577.0   
AFG           27294031.0  28004331.0  28803167.0  29708599.0  30696958.0   
AGO           21759420.0  22549547.0  23369131.0  24218565.0  25096150.0   
ALB            2947314.0   2927519.0   2913021.0   2905195.0   2900401.0   
AND              83861.0     84462.0     84449.0     83751.0     82431.0   

                    2013        2014        2015        2016        2017  
Country Code                                                              
ABW             103187.0    103795.0    104341.0    104822.0    105264.0  
AFG           31731688.0  32758020.0  33736494.0  34656032.0  35530081.0  
AGO           25998340.0  26920466.0  27859305.0  28813463.0  29784193.0  
ALB            2895092.0   2889104.0   2880703.0   2876101.0   2873457.0  
AND              80788.0     79223.0     78014.0     77281.0     76965.0  

[5 rows x 58 columns]

## Analysis

### Challenge 1: Population growth

The world population data spans from 1960 to 2017. We'd like to build a predictive model that can give us the best guess at what the population growth rate in a given year might be. We will calculate the population growth rate as follows:-

$$
Growth\_rate = \frac{current\_year\_population - previous\_year\_population}{previous\_year\_population}
$$

As such, we can only calculate the growth rate for the year 1961 onwards.

Write a function that takes the `population_df` and a `country_code` as input and computes the population growth rate for a given country starting from the year 1961. This function must return a return a 2-d numpy array that contains the year and corresponding growth rate for the country.

_**Function Specifications:**_
* Should take a `population_df` and `country_code` string as input and return a numpy `array` as output.
* The array should only have two columns containing the year and the population growth rate, in other words, it should have a shape `(?, 2)` where `?` is the length of the data.
* The growth rates should be rounded to 5 decimal places

In [19]:
def get_population_growth_rate_by_country_year(df, country_code):
    # Extract the population data for the given country code
    country_data = df.loc[country_code, '1961':]
    
    # Calculate the previous year's population values
    previous_population_values = country_data.shift(1)
    
    # Calculate the growth rates
    growth_rates = (country_data - previous_population_values) / previous_population_values
    
    # Remove the first row (since growth rate cannot be calculated for 1960)
    growth_rates = growth_rates[1:]
    
    # Extract years and growth rates
    years = growth_rates.index.astype(int)
    growth_data = np.column_stack((years, growth_rates.values))
    
    # Round the growth rates to 8 decimal places (to match expected output)
    growth_data[:, 1] = np.round(growth_data[:, 1], decimals=8)
    
    return growth_data


Input:

In [20]:
get_population_growth_rate_by_country_year(population_df,'ABW')

array([[ 1.962000e+03,  1.419604e-02],
       [ 1.963000e+03,  8.359270e-03],
       [ 1.964000e+03,  5.944090e-03],
       [ 1.965000e+03,  5.751160e-03],
       [ 1.966000e+03,  6.188980e-03],
       [ 1.967000e+03,  5.891020e-03],
       [ 1.968000e+03,  5.701490e-03],
       [ 1.969000e+03,  5.823310e-03],
       [ 1.970000e+03,  5.738510e-03],
       [ 1.971000e+03,  6.383010e-03],
       [ 1.972000e+03,  6.729480e-03],
       [ 1.973000e+03,  6.734630e-03],
       [ 1.974000e+03,  4.730840e-03],
       [ 1.975000e+03,  2.131250e-03],
       [ 1.976000e+03, -1.170520e-03],
       [ 1.977000e+03, -3.631200e-03],
       [ 1.978000e+03, -4.356760e-03],
       [ 1.979000e+03, -2.046490e-03],
       [ 1.980000e+03,  1.933980e-03],
       [ 1.981000e+03,  7.837460e-03],
       [ 1.982000e+03,  1.284528e-02],
       [ 1.983000e+03,  1.395387e-02],
       [ 1.984000e+03,  1.020884e-02],
       [ 1.985000e+03,  3.023740e-03],
       [ 1.986000e+03, -6.060990e-03],
       [ 1.987000e+03, -1

Expected output:

```
array([[ 1.961e+03,  2.263e-02],
       [ 1.962e+03,  1.420e-02],
       [ 1.963e+03,  8.360e-03],
       [ 1.964e+03,  5.940e-03],
            ...       ....
       [ 2.015e+03,  5.260e-03],
       [ 2.016e+03,  4.610e-03],
       [ 2.017e+03,  4.220e-03]])
```

### Challenge 2: Even-odd train-test split

Now that we have our data, we need to divide it into two sets: the variables we will train on and the variables we will predict on. In this scenario, we're separating the variables so that the **training set contains growth rates for even years and the test set contains growth rates for odd years**. We also need to divide our data into the predictive features (`X`) and the response features (`y`). 

Write a function that will take a 2-D numpy array as input and return four variables in the form of `(X_train, y_train), (X_test, y_test)`, where `(X_train, y_train)` are the features and response variables of the training set, and `(X_test, y_test)` are the features and response variables of the testing set. The training and testing data consist of even and odd years, respectively. The function should return two tuples of the form `(X_train, y_train), (X_test, y_test)`.

_**Function Specifications:**_
* Should take a 2-d numpy `array` as input.
* Should return two `tuples` of the form `(X_train, y_train), (X_test, y_test)`.
* `(X_train, y_train)` should consist of data from even years and `(X_test, y_test)` should consist of data from odd years.

In [27]:
def feature_response_split(arr):
    """
    Splits the data into training and testing sets based on even and odd years.

    Parameters:
    - arr (numpy array): A 2D array containing years and corresponding growth rates.

    Returns:
    - (X_train, y_train): Tuple containing training features (even years) and response variables.
    - (X_test, y_test): Tuple containing testing features (odd years) and response variables.
    """
    # Ensure the array is sorted by year
    arr = arr[arr[:, 0].argsort()]

    # Split the data into even and odd years
    even_years = arr[arr[:, 0] % 2 == 0]  # Even years for training
    odd_years = arr[arr[:, 0] % 2 != 0]   # Odd years for testing

    # Split the data into features (X) and response (y)
    X_train = even_years[:, 0]  # Even years as training features
    y_train = even_years[:, 1]  # Corresponding growth rates as training response
    X_test = odd_years[:, 0]    # Odd years as testing features
    y_test = odd_years[:, 1]    # Corresponding growth rates as testing response

    # Flatten the arrays to match the expected output
    X_train = X_train.flatten()
    X_test = X_test.flatten()

    # Return the tuples (X_train, y_train), (X_test, y_test)
    return (X_train, y_train), (X_test, y_test)

Input:

In [28]:
# Get the data for the country 'ABW'
data = get_population_growth_rate_by_country_year(population_df, 'ABW')

# Split the data into training and testing sets
(X_train, y_train), (X_test, y_test) = feature_response_split(data)

# Print the training and testing data
print("X_train:", X_train)
print("y_train:", y_train)
print("X_test:", X_test)
print("y_test:", y_test)

X_train: [1962. 1964. 1966. 1968. 1970. 1972. 1974. 1976. 1978. 1980. 1982. 1984.
 1986. 1988. 1990. 1992. 1994. 1996. 1998. 2000. 2002. 2004. 2006. 2008.
 2010. 2012. 2014. 2016.]
y_train: [ 0.01419604  0.00594409  0.00618898  0.00570149  0.00573851  0.00672948
  0.00473084 -0.00117052 -0.00435676  0.00193398  0.01284528  0.01020884
 -0.00606099 -0.01219414  0.01830187  0.05590975  0.05787267  0.03580499
  0.02136897  0.02076288  0.02254085  0.01772885  0.00800752  0.00131397
  0.00212906  0.00513459  0.00589222  0.00460988]
X_test: [1963. 1965. 1967. 1969. 1971. 1973. 1975. 1977. 1979. 1981. 1983. 1985.
 1987. 1989. 1991. 1993. 1995. 1997. 1999. 2001. 2003. 2005. 2007. 2009.
 2011. 2013. 2015. 2017.]
y_test: [ 0.00835927  0.00575116  0.00589102  0.00582331  0.00638301  0.00673463
  0.00213125 -0.0036312  -0.00204649  0.00783746  0.01395387  0.00302374
 -0.01294617 -0.0007695   0.03979147  0.0625632   0.04724902  0.02705529
  0.01979903  0.02250889  0.02131758  0.01310552  0.00384798 

Expected output:

```
y_train ==  array([ 0.01419604,  0.00594409,  0.00618898,  0.00570149,  0.00573851,
        0.00672948,  0.00473084, -0.00117052, -0.00435676,  0.00193398,
        0.01284528,  0.01020884, -0.00606099, -0.01219414,  0.01830187,
        0.05590975,  0.05787267,  0.03580499,  0.02136897,  0.02076288,
        0.02254085,  0.01772885,  0.00800752,  0.00131397,  0.00212906,
        0.00513459,  0.00589222,  0.00460988])
```

```
X_test == array([1961., 1963., 1965., 1967., 1969., 1971., 1973., 1975., 1977.,
       1979., 1981., 1983., 1985., 1987., 1989., 1991., 1993., 1995.,
       1997., 1999., 2001., 2003., 2005., 2007., 2009., 2011., 2013.,
       2015., 2017.])
```

```
y_test == array([ 0.02263378,  0.00835927,  0.00575116,  0.00589102,  0.00582331,
        0.00638301,  0.00673463,  0.00213125, -0.0036312 , -0.00204649,
        0.00783746,  0.01395387,  0.00302374, -0.01294617, -0.0007695 ,
        0.03979147,  0.0625632 ,  0.04724902,  0.02705529,  0.01979903,
        0.02250889,  0.02131758,  0.01310552,  0.00384798,  0.00098665,
        0.00377696,  0.00594675,  0.00526037,  0.00421667])      
 ```

### Question 3

Now that we have formatted our data, we can fit a model using sklearn's `DecisionTreeRegressor` class. We'll write a function that will take as input the features and response variables that we created in the last question, and return a trained model.

_**Function Specifications:**_
* Should take two numpy `arrays` as input in the form `(X_train, y_train)` as well as a `MaxDepth` int corresponding to the max_depth hyperparameter in decision trees.
* Should return an sklearn `DecisionTreeRegressor` model.
* The returned model should be fitted to the data.

_**Hint:**_
You may need to reshape the data within the function. You can use `.reshape(-1, 1)` to do this.

In [29]:

def train_model(X_train, y_train, MaxDepth):
    """
    Trains a DecisionTreeRegressor model using the provided training data.

    Parameters:
    - X_train (numpy array): The feature data (years) for training.
    - y_train (numpy array): The response data (growth rates) for training.
    - MaxDepth (int): The maximum depth of the decision tree.

    Returns:
    - model (DecisionTreeRegressor): The trained decision tree model.
    """
    # Reshape X_train to a 2D array (required by scikit-learn)
    X_train = X_train.reshape(-1, 1)
    
    # Initialize the DecisionTreeRegressor with the specified max_depth and random_state
    model = DecisionTreeRegressor(max_depth=MaxDepth, random_state=42)
    
    # Fit the model to the training data
    model.fit(X_train, y_train)
    
    # Return the trained model
    return model


Input:

In [30]:
data = get_population_growth_rate_by_country_year(population_df, 'ABW')
(X_train, y_train), _ = feature_response_split(data)

# Train the model with max_depth = 3 and random_state = 42
model = train_model(X_train, y_train, MaxDepth=3)

# Make a prediction for the year 2017
prediction = model.predict([[2017]])
print("Prediction for 2017:", prediction)

Prediction for 2017: [0.00451454]


Expected output:

```
array([0.00451454])
```

### Challenge 4

Now we would like to test our model on the testing data that we produced in Exercise 2. This test will give the Root Mean Squared Logarithmic Error (RMSLE), which is determined by:

$$
RMSLE = \sqrt{\frac{1}{N}\sum_{i=1}^N [log(1+p_i) - log(1+y_i)]^2}
$$

* *$p_i$ refers to the $i^{\rm th}$ prediction made from `X_test` 
* $y_i$ refers to the $i^{\rm th}$ value in `y_test`
* $N$ is the length of `y_test`

_**Function Specifications:**_
* Should take a trained model and two `arrays` as input. This will be the `X_test` and `y_test` variables from Question 2. 
* Should calculate and return the Root Mean Squared Logarithmic Error (RMSLE) between the predicted values from `X_test` and the actual values in `y_test`.
* The output should be a `float` rounded to 3 decimal places.



In [31]:

def test_model(model, y_test, X_test):
    # Make predictions using the trained model
    y_pred = model.predict(X_test.reshape(-1,1))
    
    # Compute the Root Mean Squared Logarithmic Error (RMSLE)
    rmsle = np.sqrt(np.mean((np.log(1+y_pred) - np.log(1+y_test))**2))
    
    # Round the RMSLE value to 3 decimal places
    rmsle_rounded = round(rmsle, 3)
    
    return rmsle_rounded


Input:

In [32]:
data = get_population_growth_rate_by_country_year(population_df,'ABW')
(X_train, y_train), (X_test, y_test) = feature_response_split(data)
lm = train_model(X_train, y_train,3)
test_model(lm, y_test, X_test)

0.007

Expected output:

```
0.007
```